'use client';

import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export function useLanguage() {
  return useContext(LanguageContext);
}

export const translations = {
  kn: {
    home: 'ಮುಖಪುಟ',
    quiz: 'ರಸಪ್ರಶ್ನೆ',
    notes: 'ಟಿಪ್ಪಣಿಗಳು',
    currentAffairs: 'ಪ್ರಚಲಿತ ವಿದ್ಯಮಾನಗಳು',
    leaderboard: 'ಪ್ರಮುಖರ ಪಟ್ಟಿ',
    profile: 'ಪ್ರೊಫೈಲ್',
    login: 'ಲಾಗಿನ್',
    logout: 'ಲಾಗ್ಔಟ್',
    adminLogin: 'ನಿರ್ವಾಹಕ ಲಾಗಿನ್',
    appName: 'ಕನ್ನಡ ಎಕ್ಸಾಂ ಪ್ರೋ',
    tagline: 'ಕೆಎಎಸ್ | ಪಿಎಸ್ಐ | ಪಿಡಿಒ | ಎಫ್ಡಿಎ | ಎಸ್ಡಿಎ',
    masterExams: 'ಕರ್ನಾಟಕ ಪರೀಕ್ಷೆಗಳಲ್ಲಿ ಪ್ರಾವೀಣ್ಯತೆ',
    dailyChallenges: 'ದೈನಂದಿನ ಚಾಲೆಂಜ್',
    mcq: 'ಪ್ರಶ್ನೆಗಳು',
    winPrizes: 'ಬಹುಮಾನ ಗೆಲ್ಲಿರಿ',
    startNow: 'ಈಗ ಪ್ರಾರಂಭಿಸಿ',
    quizDesc: '20 ಪ್ರಶ್ನೆಗಳು / ಬಹುಮಾನ ಗೆಲ್ಲಿರಿ',
    notesDesc: '50 ಪ್ರಮುಖ ಪ್ರಶ್ನೆಗಳು ಮತ್ತು ಉತ್ತರಗಳು',
    currentAffairsDesc: 'ಈಗ ನೋಡಿ',
    leaderboardDesc: 'ಪ್ರಮುಖ ವಿಜೇತರು',
    questions: 'ಪ್ರಶ್ನೆಗಳು',
    score: 'ಅಂಕ',
    previous: 'ಹಿಂದಿನ',
    next: 'ಮುಂದಿನ',
    finish: 'ಮುಕ್ತಾಯ',
    quizComplete: 'ರಸಪ್ರಶ್ನೆ ಪೂರ್ಣಗೊಂಡಿತು!',
    yourScore: 'ನಿಮ್ಮ ಸ್ಕೋರ್',
    viewAnswers: 'ಉತ್ತರಗಳನ್ನು ನೋಡಿ',
    tryAgain: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    backToHome: 'ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ',
    timeLeft: 'ಸೆಕೆಂಡುಗಳು ಉಳಿದಿವೆ',
    correct: 'ಸರಿ',
    yourAnswer: 'ನಿಮ್ಮ ಉತ್ತರ',
    detailedResults: 'ವಿವರವಾದ ಫಲಿತಾಂಶಗಳು',
    topPerformers: 'ಪ್ರಮುಖ ಪ್ರದರ್ಶಕರು',
    rank: 'ಶ್ರೇಯಾಂಕ',
    user: 'ಬಳಕೆದಾರ',
    points: 'ಅಂಕಗಳು',
    winners: 'ಕರ್ನಾಟಕದ ವಿಜೇತರು',
    viewAll: 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
    studyNotes: 'ಅಧ್ಯಯನ ಟಿಪ್ಪಣಿಗಳು',
    importantQA: 'ಪ್ರಮುಖ ಪ್ರಶ್ನೆಗಳು ಮತ್ತು ಉತ್ತರಗಳು',
    all: 'ಎಲ್ಲಾ',
    readMore: 'ಇನ್ನಷ್ಟು ಓದಿ',
    dailyUpdates: 'ದೈನಂದಿನ ನವೀಕರಣಗಳು',
    selectDate: 'ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ',
    updates: 'ನವೀಕರಣಗಳು',
    showAnswer: 'ಉತ್ತರ ತೋರಿಸಿ',
    takeDailyQuiz: 'ದೈನಂದಿನ ರಸಪ್ರಶ್ನೆ ತೆಗೆದುಕೊಳ್ಳಿ',
    welcomeBack: 'ಮತ್ತೆ ಸ್ವಾಗತ!',
    startPreparation: 'ನಿಮ್ಮ ತಯಾರಿ ಪ್ರಾರಂಭಿಸಲು ಲಾಗಿನ್ ಮಾಡಿ',
    continueWithGoogle: 'ಗೂಗಲ್ ಮುಂದುವರಿಸಿ',
    or: 'ಅಥವಾ',
    instagramId: 'ಇನ್ಸ್ಟಾಗ್ರಾಮ್ ಐಡಿ',
    enterInstagram: 'ನಿಮ್ಮ ಇನ್ಸ್ಟಾಗ್ರಾಮ್ ಬಳಕೆದಾರಹೆಸರನ್ನು ನಮೂದಿಸಿ (@ ಇಲ್ಲದೆ)',
    displayName: 'ಪ್ರದರ್ಶನ ಹೆಸರು (ಐಚ್ಛಿಕ)',
    yourName: 'ನಿಮ್ಮ ಹೆಸರು',
    loginWithInstagram: 'ಇನ್ಸ್ಟಾಗ್ರಾಮ್ ನಲ್ಲಿ ಲಾಗಿನ್ ಮಾಡಿ',
    quickDemoIds: 'ತ್ವರಿತ ಡೆಮೊ ಐಡಿಗಳು',
    adminPanel: 'ನಿರ್ವಾಹಕ ಫಲಕ',
    manageContent: 'ಪ್ರಶ್ನೆಗಳು ಮತ್ತು ಬಳಕೆದಾರರನ್ನು ನಿರ್ವಹಿಸಿ',
    dashboard: 'ಡ್ಯಾಶ್ಬೋರ್ಡ್',
    users: 'ಬಳಕೆದಾರರು',
    questions: 'ಪ್ರಶ್ನೆಗಳು',
    totalUsers: 'ಒಟ್ಟು ಬಳಕೆದಾರರು',
    totalQuestions: 'ಒಟ್ಟು ಪ್ರಶ್ನೆಗಳು',
    quizAttempts: 'ರಸಪ್ರಶ್ನೆ ಪ್ರಯತ್ನಗಳು',
    avgScore: 'ಸರಾಸರಿ ಸ್ಕೋರ್',
    addQuestion: 'ಪ್ರಶ್ನೆ ಸೇರಿಸಿ',
    edit: 'ಸಂಪಾದಿಸಿ',
    delete: 'ಅಳಿಸಿ',
    yourProfile: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್',
    totalScore: 'ಒಟ್ಟು ಸ್ಕೋರ್',
    quizzesTaken: 'ತೆಗೆದುಕೊಂಡ ರಸಪ್ರಶ್ನೆಗಳು',
    correctAnswers: 'ಸರಿ ಉತ್ತರಗಳು',
    accuracy: 'ನಿಖರತೆ',
    yourProgress: 'ನಿಮ್ಮ ಪ್ರಗತಿ',
    overallScore: 'ಒಟ್ಟಾರೆ ಸ್ಕೋರ್',
    quizCompletion: 'ರಸಪ್ರಶ್ನೆ ಪೂರ್ಣಗೊಳಿಸುವಿಕೆ',
    recentQuizHistory: 'ಇತ್ತೀಚಿನ ರಸಪ್ರಶ್ನೆ ಇತಿಹಾಸ',
    takeQuiz: 'ರಸಪ್ರಶ್ನೆ ತೆಗೆದುಕೊಳ್ಳಿ',
    quickLinks: 'ತ್ವರಿತ ಲಿಂಕ್ಗಳು',
    followUs: 'ನಮ್ಮನ್ನು ಅನುಸರಿಸಿ',
    copyright: 'ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ',
    privacyPolicy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    termsConditions: 'ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು',
    contactUs: 'ಸಂಪರ್ಕಿಸಿ',
    sessionDetails: 'ಸೆಷನ್ ವಿವರಗಳು',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    error: 'ದೋಷ ಸಂಭವಿಸಿದೆ',
    retry: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    save: 'ಉಳಿಸಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    close: 'ಮುಚ್ಚಿ',
    back: 'ಹಿಂದೆ',
    submit: 'ಸಲ್ಲಿಸಿ',
    search: 'ಹುಡುಕಿ',
    filter: 'ಫಿಲ್ಟರ್',
    advertisement: 'ಜಾಹೀರಾತು',
    adSpace: 'ಜಾಹೀರಾತು ಸ್ಥಳ',
    yourAdHere: 'ನಿಮ್ಮ ಜಾಹೀರಾತು ಇಲ್ಲಿ',
    specialOffer: 'ವಿಶೇಷ ಕೊಡುಗೆ',
    downloadApp: 'ಆಪ್ ಡೌನ್ಲೋಡ್ ಮಾಡಿ',
    premiumAccess: 'ಪ್ರೀಮಿಯಂ ಪ್ರವೇಶ',
    upgrade: 'ಅಪ್ಗ್ರೇಡ್ ಮಾಡಿ',
  },
  en: {
    home: 'Home',
    quiz: 'Quiz',
    notes: 'Notes',
    currentAffairs: 'Current Affairs',
    leaderboard: 'Leaderboard',
    profile: 'Profile',
    login: 'Login',
    logout: 'Logout',
    adminLogin: 'Admin Login',
    appName: 'Kannada Exam Pro',
    tagline: 'KAS | PSI | PDO | FDA | SDA',
    masterExams: 'Master Karnataka Exams',
    dailyChallenges: 'Daily Challenges',
    mcq: 'MCQ',
    winPrizes: 'Win Prizes',
    startNow: 'Start Now',
    quizDesc: '20 MCQ / Win Prizes',
    notesDesc: '50 imp Questions & Answers',
    currentAffairsDesc: 'Check It Now',
    leaderboardDesc: 'Top Winners',
    questions: 'Questions',
    score: 'Score',
    previous: 'Previous',
    next: 'Next',
    finish: 'Finish',
    quizComplete: 'Quiz Complete!',
    yourScore: 'Your Score',
    viewAnswers: 'View Answers',
    tryAgain: 'Try Again',
    backToHome: 'Back to Home',
    timeLeft: 'seconds left',
    correct: 'Correct',
    yourAnswer: 'Your Answer',
    detailedResults: 'Detailed Results',
    topPerformers: 'Top Performers',
    rank: 'Rank',
    user: 'User',
    points: 'points',
    winners: "Karnataka's Winners",
    viewAll: 'View All',
    studyNotes: 'Study Notes',
    importantQA: 'Important Questions & Answers',
    all: 'All',
    readMore: 'Read More',
    dailyUpdates: 'Daily Updates',
    selectDate: 'Select Date',
    updates: 'updates',
    showAnswer: 'Show Answer',
    takeDailyQuiz: 'Take Daily Quiz',
    welcomeBack: 'Welcome Back!',
    startPreparation: 'Login to start your preparation',
    continueWithGoogle: 'Continue with Google',
    or: 'OR',
    instagramId: 'Instagram ID',
    enterInstagram: 'Enter your Instagram username (without @)',
    displayName: 'Display Name (Optional)',
    yourName: 'Your name',
    loginWithInstagram: 'Login with Instagram',
    quickDemoIds: 'Quick Demo IDs',
    adminPanel: 'Admin Panel',
    manageContent: 'Manage Questions & Users',
    dashboard: 'Dashboard',
    users: 'Users',
    questions: 'Questions',
    totalUsers: 'Total Users',
    totalQuestions: 'Total Questions',
    quizAttempts: 'Quiz Attempts',
    avgScore: 'Average Score',
    addQuestion: 'Add Question',
    edit: 'Edit',
    delete: 'Delete',
    yourProfile: 'Your Profile',
    totalScore: 'Total Score',
    quizzesTaken: 'Quizzes Taken',
    correctAnswers: 'Correct Answers',
    accuracy: 'Accuracy',
    yourProgress: 'Your Progress',
    overallScore: 'Overall Score',
    quizCompletion: 'Quiz Completion',
    recentQuizHistory: 'Recent Quiz History',
    takeQuiz: 'Take Quiz',
    quickLinks: 'Quick Links',
    followUs: 'Follow Us',
    copyright: 'All rights reserved',
    privacyPolicy: 'Privacy Policy',
    termsConditions: 'Terms & Conditions',
    contactUs: 'Contact Us',
    sessionDetails: 'Session Details',
    loading: 'Loading...',
    error: 'Something went wrong',
    retry: 'Try Again',
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    back: 'Back',
    submit: 'Submit',
    search: 'Search',
    filter: 'Filter',
    advertisement: 'Advertisement',
    adSpace: 'Ad Space',
    yourAdHere: 'Your Ad Here',
    specialOffer: 'Special Offer',
    downloadApp: 'Download App',
    premiumAccess: 'Premium Access',
    upgrade: 'Upgrade',
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('kn');
  const [t, setT] = useState(translations.kn);

  useEffect(() => {
    const savedLang = localStorage.getItem('language');
    if (savedLang === 'en') {
      setLanguage('en');
      setT(translations.en);
    } else if (savedLang === 'kn') {
      setLanguage('kn');
      setT(translations.kn);
    } else {
      setLanguage('kn');
      setT(translations.kn);
      localStorage.setItem('language', 'kn');
    }
  }, []);

  const toggleLanguage = () => {
    const newLang = language === 'kn' ? 'en' : 'kn';
    setLanguage(newLang);
    setT(translations[newLang]);
    localStorage.setItem('language', newLang);
  };

  return (
    <LanguageContext.Provider value={{ language, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}
